default_connection_name = "SF_Dinesh2012"

[SF_Dinesh2012]
account = "GQB91797"
user = "dinesh2012"
password = "Din143@doc1"
database = "CORTEX_SEARCH_TUTORIAL_DB"
schema = "PUBLIC"
warehouse = "CORTEX_SEARCH_TUTORIAL_WH"
role = "ACCOUNTADMIN"

